"use client";
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { ScrollFilm } from '@/components/scroll-film';
import { ArrowDown, ArrowUpRight, Compass, MessageCircle, Trees } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

const clamp=(v:number)=>Math.max(0,Math.min(1,v));
const range=(p:number,a:number,b:number)=>clamp((p-a)/(b-a));
const ease=(v:number)=>v*v*(3-2*v);
const fade=(p:number,a:number,b:number,c:number,d:number)=>ease(range(p,a,b))*(1-ease(range(p,c,d)));
const chapters=['The Wild Coast','Five Biomes','Meet the Wild','Stay Under Stars','Experiences','Begin Journey'];
const chapterStops=[0, 0.19, 0.38, 0.57, 0.76, 0.95];
export default function Home(){
 const journey=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0);const [booking,setBooking]=useState(false);const [suite,setSuite]=useState('Valley Tented Suite');const [sent,setSent]=useState(false);const [arrival,setArrival]=useState('');
 useEffect(()=>{const root=journey.current!;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;let previous=-1;let current=-1;let lastTime=0;const els=Object.fromEntries(Array.from(root.querySelectorAll<HTMLElement>('[data-layer]')).map(el=>[el.dataset.layer!,el]));
 const paint=(now=performance.now())=>{frame=0;const target=clamp(-root.getBoundingClientRect().top/Math.max(1,root.offsetHeight-innerHeight));const dt=Math.min(64,now-lastTime||16);lastTime=now;if(current<0||reduced.matches)current=target;else current+=(target-current)*(1-Math.exp(-dt/90));if(Math.abs(target-current)<.0001)current=target;const p=current;const scene=p<.16?0:p<.33?1:p<.50?2:p<.67?3:p<.84?4:5;if(scene!==previous){previous=scene;setActive(scene)}root.style.setProperty('--progress',String(p));window.dispatchEvent(new CustomEvent('ikhaya-progress',{detail:p}));if(reduced.matches){Object.values(els).forEach(el=>{el.style.cssText='';el.removeAttribute('aria-hidden');el.inert=false});return}
 const apply=(name:string,styles:Record<string,string|number>)=>{const el=els[name];if(el)Object.assign(el.style,styles)};
 const content=(name:string,opacity:number,transform:string)=>{if(!els[name])return;apply(name,{opacity,transform});els[name].inert=opacity<.35;els[name].setAttribute('aria-hidden',String(opacity<.35))};
 const enter=ease(range(p,.28,.48)),leave=ease(range(p,.60,.74)),pool=ease(range(p,.62,.76)),end=ease(range(p,.83,.93));
 const approach=ease(range(p,.05,.28));
 apply('forest',{transform:`scale(${1+approach*.65}) translate3d(${-approach*5}%,${approach*2}%,0)`});
 apply('canopy',{opacity:(1-ease(range(p,.15,.28)))*.95,transform:`scale(${1+approach*1.25}) translate3d(${-approach*4}%,${-approach*8}%,0)`});
 apply('suite-image',{opacity:ease(range(p,.44,.52))*(1-ease(range(p,.70,.78))),clipPath:`inset(${(1-enter)*24}% ${(1-enter)*32}% ${(1-enter)*16}% ${(1-enter)*5}% round(${(1-enter)*3}px)`,transform:`translate3d(${(1-enter)*24-leave*70}%,${(1-enter)*12-leave*12}%,0) rotate(${(1-enter)*4-leave*10}deg) scale(${.88+enter*.12})`});
 apply('pool-image',{opacity:pool,clipPath:`circle(${pool*145}% at 78% 65%)`,transform:`scale(${1.25-pool*.25+end*.16})`});
 apply('return-image',{opacity:end,transform:`scale(${1.5-end*.5})`,clipPath:`inset(0 ${100-end*100}% 0 0)`});
 apply('shade',{background:`linear-gradient(90deg,rgba(4,20,16,${.48+end*.12}),rgba(4,20,16,.08)),linear-gradient(0deg,rgba(4,20,16,.65),transparent 45%)`});
 content('arrival',1-ease(range(p,.06,.15)),`translate3d(${-range(p,0,.18)*12}%,${-range(p,0,.18)*22}%,0) scale(${1+range(p,0,.18)*.2})`);
 content('biomes-copy',fade(p,.15,.20,.30,.35),`translate3d(0,${(1-ease(range(p,.12,.21)))*50-range(p,.29,.37)*55}px,0)`);
 content('wildlife-copy',fade(p,.33,.38,.48,.53),`translate3d(${(1-ease(range(p,.31,.39)))*45-range(p,.47,.55)*120}px,0,0)`);
 content('suite-copy',fade(p,.51,.56,.66,.71),`translate3d(0,${(1-ease(range(p,.49,.57)))*50-range(p,.65,.73)*60}px,0)`);
 content('experiences-copy',fade(p,.69,.74,.84,.89),`translate3d(0,${(1-ease(range(p,.67,.75)))*50-range(p,.83,.90)*60}px,0)`);
 content('last-copy',ease(range(p,.86,.93)),`translate3d(0,${(1-end)*70}px,0) scale(${.92+end*.08})`);
 apply('word',{opacity:fade(p,.12,.21,.40,.50)*.26,transform:`translate3d(${45-p*190}%,0,0)`});
 apply('postcard',{opacity:fade(p,.44,.51,.64,.72),transform:`translate3d(${(1-ease(range(p,.44,.54)))*130-range(p,.64,.74)*170}%,${(1-ease(range(p,.44,.54)))*70-range(p,.64,.74)*120}%,0) rotate(${-9+pool*13-range(p,.64,.74)*35}deg)`});
 if(Math.abs(target-current)>.0001)frame=requestAnimationFrame(paint);
 };const schedule=()=>{if(!frame)frame=requestAnimationFrame(paint)};window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);reduced.addEventListener('change',schedule);paint();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);reduced.removeEventListener('change',schedule)}},[]);
 function go(index:number){const root=journey.current!;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){root.querySelectorAll<HTMLElement>('.chapter')[index]?.scrollIntoView({behavior:'instant'});return}window.scrollTo({top:root.offsetTop+chapterStops[index]*(root.offsetHeight-innerHeight),behavior:'smooth'})}
 function reserve(name='Valley Tented Suite'){setSuite(name);setSent(false);setBooking(true)}
 return <main>
 <div className="speculative-banner">
   <span>Independent speculative concept by <strong>LocalAI Systems</strong> · Not commissioned by or affiliated with <strong>Inkwenkwezi Private Game Reserve</strong></span>
 </div>
 <header className="nav"><button className="brand" onClick={()=>go(0)} aria-label="Inkwenkwezi Private Game Reserve, return to arrival"><Compass size={26} color="#c89d5c"/><span>INKWENKWEZI<small>PRIVATE GAME RESERVE</small></span></button><span className="nav-location">CHINTSA, WILD COAST · EAST LONDON</span><button className="nav-book" onClick={()=>reserve()}>Plan your escape <ArrowUpRight size={17}/></button></header>
 <div className="journey" ref={journey}><div className="stage">
 <div className="scene-image forest" data-layer="forest"><Image src="/images/forest-lodge.webp" alt="Inkwenkwezi Private Game Reserve along the Wild Coast" fill priority unoptimized sizes="100vw"/></div>
 <div className="scene-image suite-image" data-layer="suite-image"><Image src="/images/film-suite.webp" alt="A secluded luxury tented safari suite with warm timber and panoramic bush canopy views" fill unoptimized sizes="100vw"/></div>
 <div className="scene-image pool-image" data-layer="pool-image"><Image src="/images/film-pool.webp" alt="A secluded pool overlooking coastal forest and valley bushveld" fill unoptimized sizes="100vw"/></div>
 <div className="scene-image return-image" data-layer="return-image"><Image src="/images/film-end.webp" alt="" fill unoptimized sizes="100vw"/></div>
 <ScrollFilm/>
 <div className="canopy-layer" data-layer="canopy" aria-hidden="true"><Image src="/images/canopy-overlay.webp" alt="" fill unoptimized sizes="100vw"/></div>
 <div className="shade" data-layer="shade"/>
 <div className="passing-word" data-layer="word" aria-hidden="true">untamed.</div>
 <div className="postcard" data-layer="postcard" aria-hidden="true"><Image src="/images/forest-lodge.webp" alt="" fill unoptimized sizes="30vw"/><span>WILD COAST · FIVE BIOMES.</span></div>
 <section className="chapter arrival" data-layer="arrival"><p className="eyebrow">01 / THE WILD COAST · CHINTSA</p><h1>Five worlds.<br/>One <em>wild escape.</em></h1><p className="body-copy">Where rugged coastal ocean meets untamed Eastern Cape bushveld.<br/>A protected wilderness sanctuary where time slows down.</p><button className="enter-link" onClick={()=>go(1)}>Explore the biomes <span><ArrowDown size={18}/></span></button></section>
 <section className="chapter biomes-copy" data-layer="biomes-copy"><p className="eyebrow">02 / FIVE DISTINCT BIOMES</p><h2>Five worlds.<br/><em>One reserve.</em></h2><p className="body-copy">Inkwenkwezi is home to one of Africa’s rarest ecological crossroads — five distinct biomes thriving within a single protected landscape.</p><div className="biomes-pills"><span>Tidal Estuary</span><span>Coastal Forest</span><span>Valley Bushveld</span><span>Rolling Grassland</span><span>Riverine Thicket</span></div></section>
 <section className="chapter wildlife-copy" data-layer="wildlife-copy"><p className="eyebrow">03 / WILDLIFE ENCOUNTERS</p><h2>Walk alongside<br/><em>the legends.</em></h2><p className="body-copy">From open-vehicle Big Five game drives to rare close-quarter cheetah educational experiences and 280+ indigenous bird species.</p><div className="moments"><span>Open 4×4 Game Drives</span><span>Cheetah Experience</span><span>Guided Bush Walks</span><span>Birding Safaris</span></div></section>
 <section className="chapter suite-copy" data-layer="suite-copy"><p className="eyebrow">04 / YOUR TENTED SANCTUARY</p><h2>Rest where the<br/><em>wild breathes.</em></h2><p className="body-copy">Soft linen. Elevated timber decks. An ancient indigenous canopy on the other side of the glass.</p><div className="suite-options"><button onClick={()=>reserve('Valley Tented Suite')}>Valley Tented Suite <small>2 guests · Private canopy deck</small><ArrowUpRight size={18}/></button><button onClick={()=>reserve('Bush Tented Suite')}>Bush Tented Suite <small>Family retreat · Valley bushveld</small><ArrowUpRight size={18}/></button></div></section>
 <section className="chapter experiences-copy" data-layer="experiences-copy"><p className="eyebrow">05 / CHOOSE YOUR ESCAPE</p><h2>Tailored for<br/><em>every journey.</em></h2><p className="body-copy">Whether arriving for a luxury weekend, a day game drive, or an unforgettable celebration.</p><div className="experience-cards"><div className="experience-card" onClick={()=>reserve('Luxury Safari Stay')}><span className="card-badge">Accommodation</span><h3>Luxury Safari Stays</h3><p>Elevated valley tented suites with private decks and boma dinners under the stars.</p><span className="card-link">Explore suites <ArrowUpRight size={14}/></span></div><div className="experience-card" onClick={()=>reserve('Day Safari & Game Drive')}><span className="card-badge">Day Visitors</span><h3>Game Drives & Safaris</h3><p>3-hour guided 4×4 game drives, cheetah educational encounters & sunset tours.</p><span className="card-link">Book safari <ArrowUpRight size={14}/></span></div><div className="experience-card" onClick={()=>reserve('Weddings & Events')}><span className="card-badge">Celebrations</span><h3>Weddings & Events</h3><p>Open-air forest chapel, panoramic reception hall, and conferences for up to 180 guests.</p><span className="card-link">Plan event <ArrowUpRight size={14}/></span></div></div></section>
 <section className="chapter last-copy" data-layer="last-copy"><p className="eyebrow">06 / YOUR WILD COAST JOURNEY</p><h2>Your wild escape<br/><em>awaits.</em></h2><div className="cta-actions"><button className="pill light" onClick={()=>reserve()}>Preview reservation <ArrowUpRight size={18}/></button><a href="https://wa.me/27437343234?text=Hi%20Inkwenkwezi,%20I'm%20enquiring%20about%20a%20stay%20and%20safari%20experience" target="_blank" rel="noopener noreferrer" className="pill whatsapp"><MessageCircle size={18}/> Chat on WhatsApp</a></div><p className="concept">Independent speculative concept by LocalAI Systems · Not commissioned by or affiliated with Inkwenkwezi Private Game Reserve</p><button className="again" onClick={()=>go(0)}>Wander back to the beginning</button></section>
 <div className="scene-footer"><span className="place-note">FIVE WORLDS. ONE WILD ESCAPE.</span><nav className="chapters" aria-label="Journey chapters">{chapters.map((name,i)=><button key={name} aria-current={active===i?'step':undefined} onClick={()=>go(i)}><span className="chapter-number">0{i+1}</span><span className="chapter-name">{name}</span></button>)}</nav><span className="scroll-cue">SCROLL TO WANDER <ArrowDown size={14}/></span></div>
 <div className="progress-track"><div className="progress-fill"/></div>
 </div></div>
 <Dialog open={booking} onOpenChange={setBooking}><DialogContent className="booking"><DialogTitle className="booking-title">Reserve your escape.</DialogTitle><DialogDescription>Independent speculative concept by LocalAI Systems. Explore Inkwenkwezi safari and accommodation below; no booking or enquiry will be sent.</DialogDescription>{sent?<div className="confirmation" role="status"><Compass size={40} color="#c89d5c"/><h3>Your escape, imagined.</h3><p>{suite}, arriving {arrival}. A real reservation or direct WhatsApp channel can be connected here.</p><button className="pill" onClick={()=>setBooking(false)}>Back to the reserve</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Your hideaway<select value={suite} onChange={e=>setSuite(e.target.value)}><option>Valley Tented Suite</option><option>Bush Tented Suite</option></select></label><div className="date-grid"><label>Arrival<input type="date" required min={new Date().toLocaleDateString('en-CA')} value={arrival} onChange={e=>setArrival(e.target.value)}/></label><label>Guests<select><option>2 guests</option><option>1 guest</option>{suite==='Bush Tented Suite'&&<><option>3 guests</option><option>4 guests</option></>}</select></label></div><button className="pill" type="submit">Preview my safari stay <ArrowUpRight size={17}/></button></form>}</DialogContent></Dialog> </main>
}
